### ISSUE TITLE
Page is wider than intended on mobile

### ISSUE THREAD

**Issue by danrabbit** [danrabbit/danrabbit.github.io#10]
something to do with footer padding. Unsure what's going on.

**Comment by marijnvdwerf** [comment]
Did you already try `box-sizing: border-box` combined with `width: 100%`?

**Comment by marijnvdwerf** [comment]
Also, if it's an iOS-only thing, you could look at https://developer.apple.com/library/ios/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html
