### ISSUE TITLE
"isn't" not "doesn't

### ISSUE THREAD

**Issue by TraumaD91** [danrabbit/danrabbit.github.io#3]
"Dan is a pretty cool guy. He writes computer software and <b>isn't</b> afraid of anything." ;p

**Comment by danrabbit** [comment]
haha, this is done purposefully http://knowyourmeme.com/memes/pretty-cool-guy

**Comment by TraumaD91** [comment]
Oh lol. Sorry, I was not aware of this meme. <iframe src="//giphy.com/embed/xTiTno1ju4OXEUL5Sg" width="480" height="348" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/90s-will-smith-the-more-you-know-xTiTno1ju4OXEUL5Sg">via GIPHY</a></p>
