### ISSUE TITLE
Social Button Misalignment

### ISSUE THREAD

**Issue by Foggalong** [danrabbit/danrabbit.github.io#6]
If social buttons are turned off (through a browser extension for example) then only the symbols disappear, not the whole button itself. Not sure if this is something that can be fixed, but thought it was worth sharing none the less.
![screenshot_2016-01-31_17-18-26](https://cloud.githubusercontent.com/assets/5920259/12703596/f168ef22-c83e-11e5-9478-d67012cf1927.png)

**Comment by danrabbit** [comment]
Gonna mark "Won't Fix". Your browser extension is breaking muh website

**Comment by Foggalong** [comment]
That's fair enough :)
